server:
  port: 10002
spring:
  application:
    name: resource #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.27.63.0:3306/resource?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
#    username: root
#    password: 35f3eac33f6f79db
    url: jdbc:mysql://127.0.0.1:3306/resource?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    druid:
      initial-size: 2
      max-active: 5
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        allow:
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
        slf4j:
          enabled: true
  redis:
    database: 0
    host: 120.27.63.0
    password: bd9d78
    port: 6379
mybatis-plus:
  configuration:
    local-cache-scope: statement

