server:
  port: 10000
spring:
  application:
    name: xxl-job #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.63.0:3306/monolith?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: monolith
    password: y3whAM3CtdM2W88A
    druid:
      initial-size: 2
      max-active: 5
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        allow:
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
        slf4j:
          enabled: true
xxl:
  job:
    admin:
      addresses: http://120.27.63.0:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job
      address:
      ip:
      port: 9989
      logpath: D:\Workspace\Java\monolith\monolith-complex\monolith-complex-xxl-job\src\main\java\com\mochen\xxl\log
      logretentiondays: 30

