server:
  port: 10000
spring:
  application:
    name: web #应用名字
  jackson:
    date-format: yyyy‐MM‐dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://120.27.63.0:27017/monolith
